../rtl/REGISTER/THCSR_REG.v
../rtl/REGISTER/TISR_REG.v
../rtl/REGISTER/TIER_REG.v
../rtl/REGISTER/TCR_REG.v
../rtl/REGISTER/TCMP0_REG.v
../rtl/REGISTER/TCMP1_REG.v
../rtl/REGISTER/TDR0_REG.v
../rtl/REGISTER/TDR1_REG.v
../rtl/REGISTER/REGISTER.v

../rtl/COUNTER/ROM.v
../rtl/COUNTER/COUNTER.v

../rtl/APB/APB_SLAVE.v

../rtl/TIMER_TOP/TIMER_TOP.v
